<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PocketFrame.Automation\PocketFrame.Automation.csproj" />
    <ProjectReference Include="..\PocketFrame.Environments\PocketFrame.Environments.csproj" />
    <ProjectReference Include="..\PocketFrame.Scenarios\PocketFrame.Scenarios.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
